### ISSUE TITLE
New CKAN URL

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5-mediasuite#51]
Make sure it is changed from current URL (http://52.89.136.166/) to new one: http://mediasuitedata.clariah.nl/

**Comment by lilimelgar** [comment]
& redirect old one to new one (the link has been provided in several presentations).

**Comment by jblom** [comment]
I only found one reference to the old URL (the IP address) in the mediasuite (in the running text of the data sources page. The button already was linking to the right thing).

Also redirection from the old IP to the new one, is a bit tricky. I think it's best to just forget about the disseminated links, since 1) the media suite will probably be the central point of entry and 2) there are many more occasions where the proper URL to CKAN can be propagated.
